"""initial schema

Revision ID: e326f0cf24f7
Revises:
Create Date: 2026-07-28 12:13:52.244446
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'e326f0cf24f7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_zh', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_tone', sa.String(length=40), nullable=False),
    sa.Column('base_spirit', sa.String(length=100), nullable=False),
    sa.Column('glass_type', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=False),
    sa.Column('alcohol_level', sa.String(length=30), nullable=False),
    sa.Column('flavor_sweet', sa.Integer(), nullable=False),
    sa.Column('flavor_sour', sa.Integer(), nullable=False),
    sa.Column('flavor_bitter', sa.Integer(), nullable=False),
    sa.Column('flavor_strong', sa.Integer(), nullable=False),
    sa.Column('flavor_fresh', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=False),
    sa.Column('popularity_weight', sa.Float(), nullable=False),
    sa.Column('beginner_friendly', sa.Boolean(), nullable=False),
    sa.Column('is_iba', sa.Boolean(), nullable=False),
    sa.Column('is_alcoholic', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cocktails_slug'), 'cocktails', ['slug'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_zh', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_household_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_slug'), 'ingredients', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('anonymous_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_anonymous_key'), 'users', ['anonymous_key'], unique=True)
    op.create_table('cocktail_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cocktail_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.String(length=80), nullable=False),
    sa.Column('requirement', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cocktail_id', 'ingredient_id', 'display_order')
    )
    op.create_table('cocktail_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cocktail_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('technique', sa.String(length=80), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('tip', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cocktail_id', 'step_number')
    )
    op.create_table('cocktail_view_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cocktail_id', sa.String(length=36), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cocktail_id')
    )
    op.create_table('daily_picks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pick_date', sa.Date(), nullable=False),
    sa.Column('cocktail_id', sa.String(length=36), nullable=False),
    sa.Column('weight_snapshot', sa.Float(), nullable=True),
    sa.Column('reason_snapshot', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pick_date')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cocktail_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'cocktail_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('daily_picks')
    op.drop_table('cocktail_view_history')
    op.drop_table('cocktail_steps')
    op.drop_table('cocktail_ingredients')
    op.drop_index(op.f('ix_users_anonymous_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ingredients_slug'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_cocktails_slug'), table_name='cocktails')
    op.drop_table('cocktails')
    # ### end Alembic commands ###
